version: '3.1'
services:

  db:
    image: postgres
    environment:
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "15432:80"
    depends_on:
      - db

volumes:
  postgres:
  pgadmin:
